# Generated by Django 5.2.7 on 2025-10-31 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_goals', models.IntegerField(blank=True, null=True)),
                ('own_position', models.IntegerField(blank=True, null=True)),
                ('own_manager_name', models.TextField(blank=True, null=True)),
                ('opponent_goals', models.IntegerField(blank=True, null=True)),
                ('opponent_position', models.IntegerField(blank=True, null=True)),
                ('opponent_manager_name', models.TextField(blank=True, null=True)),
                ('hosting', models.TextField(blank=True, null=True)),
                ('is_win', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'club_games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerValuations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('market_value_in_eur', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_valuations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_season', models.TextField(blank=True, null=True)),
                ('from_club_name', models.TextField(blank=True, null=True)),
                ('to_club_name', models.TextField(blank=True, null=True)),
                ('transfer_fee', models.FloatField(blank=True, null=True)),
                ('market_value_in_eur', models.FloatField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('competition_id', models.TextField(primary_key=True, serialize=False)),
                ('competition_code', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('sub_type', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('domestic_league_code', models.TextField(blank=True, null=True)),
                ('confederation', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('is_major_national_league', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_code', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('total_market_value', models.FloatField(blank=True, null=True)),
                ('squad_size', models.IntegerField(blank=True, null=True)),
                ('average_age', models.FloatField(blank=True, null=True)),
                ('foreigners_number', models.IntegerField(blank=True, null=True)),
                ('foreigners_percentage', models.FloatField(blank=True, null=True)),
                ('national_team_players', models.IntegerField(blank=True, null=True)),
                ('stadium_name', models.TextField(blank=True, null=True)),
                ('stadium_seats', models.IntegerField(blank=True, null=True)),
                ('net_transfer_record', models.TextField(blank=True, null=True)),
                ('coach_name', models.TextField(blank=True, null=True)),
                ('last_season', models.IntegerField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('domestic_competition_id', models.ForeignKey(blank=True, db_column='domestic_competition_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.competitions')),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('round', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('home_club_goals', models.IntegerField(blank=True, null=True)),
                ('away_club_goals', models.IntegerField(blank=True, null=True)),
                ('home_club_position', models.IntegerField(blank=True, null=True)),
                ('away_club_position', models.IntegerField(blank=True, null=True)),
                ('home_club_manager_name', models.TextField(blank=True, null=True)),
                ('away_club_manager_name', models.TextField(blank=True, null=True)),
                ('stadium', models.TextField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('referee', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('home_club_formation', models.TextField(blank=True, null=True)),
                ('away_club_formation', models.TextField(blank=True, null=True)),
                ('home_club_name', models.TextField(blank=True, null=True)),
                ('away_club_name', models.TextField(blank=True, null=True)),
                ('aggregate', models.TextField(blank=True, null=True)),
                ('competition_type', models.TextField(blank=True, null=True)),
                ('away_club_id', models.ForeignKey(blank=True, db_column='away_club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_games', to='main.clubs')),
                ('competition_id', models.ForeignKey(blank=True, db_column='competition_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.competitions')),
                ('home_club_id', models.ForeignKey(blank=True, db_column='home_club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_games', to='main.clubs')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('last_season', models.IntegerField(blank=True, null=True)),
                ('player_code', models.TextField(blank=True, null=True)),
                ('country_of_birth', models.TextField(blank=True, null=True)),
                ('city_of_birth', models.TextField(blank=True, null=True)),
                ('country_of_citizenship', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('sub_position', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('foot', models.TextField(blank=True, null=True)),
                ('height_in_cm', models.IntegerField(blank=True, null=True)),
                ('contract_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('agent_name', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('current_club_name', models.TextField(blank=True, null=True)),
                ('market_value_in_eur', models.IntegerField(blank=True, null=True)),
                ('highest_market_value_in_eur', models.IntegerField(blank=True, null=True)),
                ('current_club_domestic_competition_id', models.ForeignKey(blank=True, db_column='current_club_domestic_competition_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.competitions')),
                ('current_club_id', models.ForeignKey(blank=True, db_column='current_club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.clubs')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='GameLineups',
            fields=[
                ('game_lineups_id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('team_captain', models.IntegerField(blank=True, null=True)),
                ('club_id', models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.clubs')),
                ('game_id', models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.games')),
                ('player_id', models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.players')),
            ],
            options={
                'db_table': 'game_lineups',
            },
        ),
        migrations.CreateModel(
            name='GameEvents',
            fields=[
                ('game_event_id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('club_id', models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.clubs')),
                ('game_id', models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.games')),
                ('player_assist_id', models.ForeignKey(blank=True, db_column='player_assist_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_events_as_assister', to='main.players')),
                ('player_id', models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.players')),
                ('player_in_id', models.ForeignKey(blank=True, db_column='player_in_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_events_as_substitute', to='main.players')),
            ],
            options={
                'db_table': 'game_events',
            },
        ),
        migrations.CreateModel(
            name='Appearances',
            fields=[
                ('appearance_id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('minutes_played', models.IntegerField(blank=True, null=True)),
                ('player_club_id', models.ForeignKey(blank=True, db_column='player_club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appearances_as_player_club', to='main.clubs')),
                ('player_current_club_id', models.ForeignKey(blank=True, db_column='player_current_club_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appearances_as_current_club', to='main.clubs')),
                ('competition_id', models.ForeignKey(blank=True, db_column='competition_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.competitions')),
                ('game_id', models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.games')),
                ('player_id', models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.players')),
            ],
            options={
                'db_table': 'appearances',
            },
        ),
    ]
